### ISSUE TITLE
Add unit tests for schema checker developed in #11

### ISSUE THREAD

**Issue by isedwards** [opencdms-dev/pyopencdms-old#12]
This issues aims to add tests for the schema checker developed in #11

Specifically, we need a way to:
- [ ] Create a small test SQLAlchemy ORM model (e.g. a single small table)
- [ ] Create an empty SQLite test database
- [ ] Create the corresponding table in SQLite
- [ ] Run a test that confirms the database schema is the same as the model
- [ ] Alter the database schema (see examples in #11)
- [ ] Run a test that confirms that the schema check detects and correctly reports the difference.

**Comment by isedwards** [comment]
pyopencdms aims to support the same Python 3.x versions that our major dependencies support.

In the case of SQLAlchemy, [version 1.4 and above](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#change-5634) support Python 3.6 and above (with support for Python 2.x being dropped in SQLAlchemy 2.0).

We do not intend to support Python 2.x

SQLAlchemy uses tox (and virtualenv) to test against multiple Python versions and different database backends.

**Comment by Shaibujnr** [comment]
https://github.com/opencdms/pyopencdms/pull/21

Run `pip install pytest`
Run 'make test`

**Comment by isedwards** [comment]
Resolved by #21 and #22
