### ISSUE TITLE
Switch to using poetry for packaging

### ISSUE THREAD

**Issue by isedwards** [opencdms-dev/pyopencdms-old#30]
Presumably using poetry means we can remove twine from requirements_dev?

**Comment by Shaibujnr** [comment]
Yeah. We won't need that anymore.

**Comment by Shaibujnr** [comment]
https://github.com/opencdms/pyopencdms/pull/32

**Comment by isedwards** [comment]
@Shaibujnr could you check why the tests are failing after the switch to poetry:
`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-yj89x2na/README.md'`

**Comment by Shaibujnr** [comment]
https://github.com/opencdms/pyopencdms/pull/36

**Comment by isedwards** [comment]
Resolved by #36
