### ISSUE TITLE
Return datetime.datetime objects from sqlalchemy for datetime/timestamp columns

### ISSUE THREAD

**Issue by faysal-ishtiaq** [opencdms-dev/pyopencdms-old#42]
`pyopencdms` sqlalchemy models should return `datetime.datetime` objects for any column of type `datetime` or `timestamp` for any of supported CDMS providers.

**Comment by isedwards** [comment]
Could you add a link to the part of the Climsoft model where this is not currently happening?

**Comment by isedwards** [comment]
Further checks confirm behaviour is already as expected: SQLAlchemy returns Python `datetime.datetime` objects for database DATETIME type.
