### ISSUE TITLE
Failed to install on Mysqlclient package on Ubuntu

### ISSUE THREAD

**Issue by chinedu117** [opencdms-dev/pyopencdms-old#54]
* opencdms version: 10
* Python version: 3.9.5
* Operating System: Ubuntu Linux

### Description

I was trying to install pyopencdms requirements on my  machine. 
It failed when trying to install mysqlclient.

### What I Did

```
$ cd pyopencdms
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install -r requirements.txt

```

**Comment by isedwards** [comment]
Closed by #55
